version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - 'shared:/app/node_modules'
    environment:
      - NODE_ENV=production
    command: npm start

volumes:
  shared: